# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [116]:
# Completar o exercício aqui
import numpy as np
print("Array de elementos de 10 a 100")
array_elementos = np.array(range(10, 101))
print(array_elementos)
print("Array de elementos de 10 a 100 invertido a ordem")
array_invertido = np.flip(array_elementos)
print(array_invertido)
print("Array 3x3 com valores de 0 a 8 com 2 dimensões")
array_3x3 = np.arange(3 * 3).reshape(3, 3)
print(array_3x3)
print("Array identidade de 6x6")
array_identidade = np.identity(6)
print(array_identidade)
print("Array com valores aleatórios 3x3x3")
array_3x3x3 = np.random.randn((3 * 3 * 3)).reshape(3, 3, 3)
print(array_3x3x3)
# criando 2 arrays quaisquer de 5 dimensões 5x5
array_A = np.random.randn((5 * 5 * 5 * 5 * 5)).reshape(5, 5, 5, 5, 5)
array_B = np.random.randn((5 * 5 * 5 * 5 * 5)).reshape(5, 5, 5, 5, 5)
# print("Array A")
# print(array_A)
# print("Array B")
# print(array_B)
# Alguns métodos de comparação entre 2 arrays
print("Testa se os arrays A e B tem a mesma forma e os valores de todos elementos são iguais.")
print(np.array_equal(array_A, array_B))
print("Testa se os arrays A e B tem a forma equivalente se convertida e os valores de todos elementos são iguais.")
print(np.array_equiv(array_A, array_B))
print("Testa se os arrays A e B tem a mesma forma e os valores de todos elementos são próximos o bastante.")
print(np.allclose(array_A, array_B))
print("Testa se os arrays A e B tem a mesma forma.")
print(array_A.shape == array_B.shape)
print("Testa se são os arrays A e B são exatamente iguais, contudo pode produzir resultados inesperados, se tiver elementos vazios ou o tamanho de um array for diferente do outro. (Não recomendado)")
print((array_A == array_B).all())


Array de elementos de 10 a 100
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
Array de elementos de 10 a 100 invertido a ordem
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]
Array 3x3 com valores de 0 a 8 com 2 dimensões
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array identidade de 6x6
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.

**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Fazer a conversão dos preços em dólares do primeiro array para um segundo array que se vai chamar euros. Devemos utilizar a  seguinte conversão: 
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, arredondando a 2 casas decimais.

In [117]:
# Completar o exercício aqui
import numpy as np
dólares = np.random.randint(low=1, high=1000, size=100)
print("Dólares:\n", dólares, sep="")
taxa_conversão_USD_EUR = 0.874413
euros = dólares * taxa_conversão_USD_EUR
print("Euros com valores arrendondados a 2 casas decimais:\n",
      np.round(euros, 2), sep="")


Dólares:
[106 406  85 986 439 873 905 300 836   8 455 898 625 148 436 928 284 357
 319 139 321 211 809 840 976 955 308 956 532 292 885 529 446 470 519 126
  71 535 820 502 860 381 432 220 865 140 912 235 324 246 994 535 440 468
 129 802 957 186 121 437  14  15 791 724 498 134 316 656 909 193 146 123
 958 606 477 652 866 233 911 922 984 153  19 563 887 232 558 764 671  43
 777  92 961 855 173  24 518 894 718 244]
Euros com valores arrendondados a 2 casas decimais:
[ 92.69 355.01  74.33 862.17 383.87 763.36 791.34 262.32 731.01   7.
 397.86 785.22 546.51 129.41 381.24 811.46 248.33 312.17 278.94 121.54
 280.69 184.5  707.4  734.51 853.43 835.06 269.32 835.94 465.19 255.33
 773.86 462.56 389.99 410.97 453.82 110.18  62.08 467.81 717.02 438.96
 752.   333.15 377.75 192.37 756.37 122.42 797.46 205.49 283.31 215.11
 869.17 467.81 384.74 409.23 112.8  701.28 836.81 162.64 105.8  382.12
  12.24  13.12 691.66 633.08 435.46 117.17 276.31 573.61 794.84 168.76
 127.66 107.55 837.69 529.89 417.1  5

**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos.
* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos
* Mostrar o número de registos do dataframe de títulos.
* Mostrar o número de registos do dataframe de elenco.
* Mostrar os 5 titulos mais antigas.
* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
* Mostrar os 10 títulos mais comuns (que mais se repetem).
* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
* Mostrar quantos filmes foram feitas no ano 1950.
* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
* Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).
* Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.
* Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
* Mostrar quantos papéis fez “Robert de Niro” na sua carreira.
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente.
* Mostrar quantos papéis para atores teve na década 50’s.
* Mostrar quantos papéis para atrizes teve na década 50’s.

In [2]:
# Completar o exercício aqui
import pandas as pd
import re
dataframe_títulos = pd.read_csv('05_05_imdb_titulos.csv')
print("\nMostrando os 5 primeiros registos de títulos:")
print(dataframe_títulos.head(5))

dataframe_elenco = pd.read_csv('05_05_imdb_elenco.csv')
print("\nMostrando os 5 primeiros registos de elenco:")
print(dataframe_elenco.head(5))

print("\nNúmero de registos do dataframe de títulos.\n",
      dataframe_títulos.count()[0], sep="")
print("\nNúmero de registos do dataframe de elenco.\n",
      dataframe_elenco.count()[0], sep="")

dataframe_títulos.sort_values(by=['year'], inplace=True, ascending=True)
print("5 títulos mais antigos:")
print(dataframe_títulos.head(5))

dracula_filmes = dataframe_títulos[dataframe_títulos['title'].str.contains("Dracula") | dataframe_títulos['title'].str.contains(
    "Drácula") | dataframe_títulos['title'].str.contains("dracula") | dataframe_títulos['title'].str.contains("drácula")]
print("\nFilmes que no título contém a expressão 'Drácula':\n",
      dracula_filmes, sep="")
print("\nNúmero total de filmes com a expressão 'Drácula':",
      dracula_filmes.count()[0])

# 10 títulos mais comuns através de uma das maneiras possíveis
# print(dataframe_títulos['title'].value_counts().sort_values(ascending=False).head(10))

# 10 títulos mais comuns por outro método e atinge o mesmo resultado
groupby_títulos = dataframe_títulos.groupby(
    'title')['title'].count().sort_values(ascending=False)
print("10 títulos mais comuns:")
print(groupby_títulos.head(10))


primeiro_romeo_julieta = dataframe_títulos[dataframe_títulos.title == 'Romeo and Juliet'].sort_values(
    by=['year'], ascending=True).head(1)
print("Primeiro filme chamado 'Romeo and Juliet':")
print(primeiro_romeo_julieta)

exorcist_filmes = dataframe_títulos[dataframe_títulos['title'].str.contains(
    "Exorcist") | dataframe_títulos['title'].str.contains("exorcist")].sort_values(by=['year'], ascending=True)
print("Filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente:")
print(exorcist_filmes)

filmes_1950 = dataframe_títulos[dataframe_títulos.year == 1950]
print(f"Filmes feitos em 1950, um total de {len(filmes_1950)}:")
print(filmes_1950)

filmes_1950_1959 = dataframe_títulos.loc[(dataframe_títulos['year'] >= 1950) & (
    dataframe_títulos['year'] <= 1959)].sort_values(by=['year'], ascending=True)
print(f"Filmes feitos de 1950 a 1959, um total de {len(filmes_1950_1959)}:")
print(filmes_1950_1959)

the_godfather_papeis = dataframe_elenco.loc[(dataframe_elenco['title'] == "The Godfather") | (
    dataframe_elenco['title'].str.contains("The Godfather: "))].groupby(['character'])['character'].count()
print("Papéis que teve a trilogia “The Godfather”, agrupando pelo papel e com a informação da quantidade de vezes que esse papel apareceu no total da trilogia:")
print(the_godfather_papeis)

elenco_dracula = dataframe_elenco.loc[(dataframe_elenco['title'] == "Dracula") & (
    dataframe_elenco['year'] == 1958)].sort_values(by=['n'], ascending=True)
print('Elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958:')
print(elenco_dracula)

# Usando regex para filtrar os papéis de Bruce Wayne e variantes
# os testes para encontrar o regex ideal foram feitos em https://regex101.com/
bruce_wayne_papeis = dataframe_elenco.loc[(dataframe_elenco['character'].str.contains(
    pat="(?:Young.*)?(?:Bruce Wayne(?:.*age.*)?)$", regex=True))]
print(
    f"Papéis de Bruce Wayne como protagonista, um total de {len(bruce_wayne_papeis)}")
print(bruce_wayne_papeis)


robert_niro_papeis = dataframe_elenco.loc[(
    dataframe_elenco['name'] == 'Robert De Niro')]
print(
    f"Papéis que “Robert De Niro” fez na sua carreira, um total de {len(robert_niro_papeis)}:")
print(robert_niro_papeis)

charlton_heston = dataframe_elenco.loc[(dataframe_elenco['name'] == 'Charlton Heston') & (dataframe_elenco['year'] >= 1960) & (
    dataframe_elenco['year'] <= 1969) & (dataframe_elenco['n'] == 1)].sort_values(by=['year'], ascending=False)
print(
    f"Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente. Um total de {len(charlton_heston)}:")
print(charlton_heston)

atores_50s = dataframe_elenco.loc[(dataframe_elenco['type'] == "actor") & (
    dataframe_elenco['year'] >= 1950) & (dataframe_elenco['year'] <= 1959)].groupby(['name'])['name'].count().sort_values(ascending=False)
print("Quantos papéis para cada um dos atores na década 50’s:")
print(atores_50s)

atrizes_50s = dataframe_elenco.loc[(dataframe_elenco['type'] == "actress") & (
    dataframe_elenco['year'] >= 1950) & (dataframe_elenco['year'] <= 1959)].groupby(['name'])['name'].count().sort_values(ascending=False)
print("Quantos papéis para cada uma das atrizes na década 50’s:")
print(atrizes_50s)



Mostrando os 5 primeiros registos de títulos:
                                   title  year
0                                 Mahler  1974
1           Ogon, voda i... mednye truby  1968
2  Ana Nojoom bent alasherah wamotalagah  2014
3                      Malu de Bicicleta  2010
4             Nazareno Apostol: Boy Ahas  1989

Mostrando os 5 primeiros registos de elenco:
                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN

Número de registos do dataframe de títulos.
230407

Número de registos do dataframe de elenco.
3564650
5 títulos mais antigos:
                             