# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [70]:
# Completar o exercício aqui
import numpy as np
print("Array de elementos de 10 a 100")
array_elementos = np.array(range(10, 101))
print(array_elementos)
print("Array de elementos de 10 a 100 invertido a ordem")
array_invertido = np.flip(array_elementos)
print(array_invertido)
print("Array 3x3 com valores de 0 a 8 com 2 dimensões")
array_3x3 = np.arange(3 * 3).reshape(3, 3)
print(array_3x3)
print("Array identidade de 6x6")
array_identidade = np.identity(6)
print(array_identidade)
print("Array com valores aleatórios 3x3x3")
array_3x3x3 = np.random.randn((3 * 3 * 3)).reshape(3, 3, 3)
print(array_3x3x3)
# criando 2 arrays quaisquer de 5 dimensões 5x5
array_A = np.random.randn((5 * 5 * 5 * 5 * 5)).reshape(5, 5, 5, 5, 5)
array_B = np.random.randn((5 * 5 * 5 * 5 * 5)).reshape(5, 5, 5, 5, 5)
# print("Array A")
# print(array_A)
# print("Array B")
# print(array_B)
# Alguns métodos de comparação entre 2 arrays
print("Testa se os arrays A e B tem a mesma forma e os valores de todos elementos são iguais.")
print(np.array_equal(array_A, array_B))
print("Testa se os arrays A e B tem a forma equivalente se convertida e os valores de todos elementos são iguais.")
print(np.array_equiv(array_A, array_B))
print("Testa se os arrays A e B tem a mesma forma e os valores de todos elementos são próximos o bastante.")
print(np.allclose(array_A, array_B))
print("Testa se os arrays A e B tem a mesma forma.")
print(array_A.shape == array_B.shape)
print("Testa se são os arrays A e B são exatamente iguais, contudo pode produzir resultados inesperados, se tiver elementos vazios ou o tamanho de um array for diferente do outro. (Não recomendado)")
print((array_A == array_B).all())


Array de elementos de 10 a 100
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
Array de elementos de 10 a 100 invertido a ordem
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]
Array 3x3 com valores de 0 a 8 com 2 dimensões
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array identidade de 6x6
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.

**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Fazer a conversão dos preços em dólares do primeiro array para um segundo array que se vai chamar euros. Devemos utilizar a  seguinte conversão: 
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, arredondando a 2 casas decimais.

In [87]:
# Completar o exercício aqui
import numpy as np
dólares = np.random.randint(low=1, high=1000, size=100)
print("Dólares:\n", dólares, sep="")
taxa_conversão_USD_EUR = 0.874413
euros = dólares * taxa_conversão_USD_EUR
print("Euros com valores arrendondados a 2 casas decimais:\n",
      np.round(euros, 2), sep="")


Dólares:
[885 586 939 582 305 384 406 444 681 598 163 156 201  65 896 929 742 166
 610 114 589  16 109 344  21 938 595 995 837 347  36 994 815  77 203 304
 216 930 673 359 302 219 156 823 749 922 587 532 361 152 787 563 281 278
 719 871 759 661 816 443 480 781 396 454 699 695  21 981 974 221 951 829
 798 647 344 140 197  50 784 380 317 905 191 349 892 542 122 298 783 828
   5 393 485 246 711 459 714 261 748 211]
Euros com valores arrendondados a 2 casas decimais:
[773.86 512.41 821.07 508.91 266.7  335.77 355.01 388.24 595.48 522.9
 142.53 136.41 175.76  56.84 783.47 812.33 648.81 145.15 533.39  99.68
 515.03  13.99  95.31 300.8   18.36 820.2  520.28 870.04 731.88 303.42
  31.48 869.17 712.65  67.33 177.51 265.82 188.87 813.2  588.48 313.91
 264.07 191.5  136.41 719.64 654.94 806.21 513.28 465.19 315.66 132.91
 688.16 492.29 245.71 243.09 628.7  761.61 663.68 577.99 713.52 387.36
 419.72 682.92 346.27 396.98 611.21 607.72  18.36 857.8  851.68 193.25
 831.57 724.89 697.78 565.75 300.8  

**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos.
* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos
* Mostrar o número de registos do dataframe de títulos.
* Mostrar o número de registos do dataframe de elenco.
* Mostrar os 5 titulos mais antigas.
* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
* Mostrar os 10 títulos mais comuns (que mais se repetem).
* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
* Mostrar quantos filmes foram feitas no ano 1950.
* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
* Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).
* Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.
* Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
* Mostrar quantos papéis fez “Robert de Niro” na sua carreira.
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente.
* Mostrar quantos papéis para atores teve na década 50’s.
* Mostrar quantos papéis para atrizes teve na década 50’s.

In [181]:
# Completar o exercício aqui
import pandas as pd
# dataframe_títulos = pd.read_csv('05_05_imdb_titulos.csv')
# print("\nMostrando os 5 primeiros registos de títulos:")
# print(dataframe_títulos.head(5))

# dataframe_elenco = pd.read_csv('05_05_imdb_elenco.csv')
# print("\nMostrando os 5 primeiros registos de elenco:")
# print(dataframe_elenco.head(5))

# print("\nNúmero de registos do dataframe de títulos.\n",
#       dataframe_títulos.count()[0], sep="")
# print("\nNúmero de registos do dataframe de elenco.\n",
#       dataframe_elenco.count()[0], sep="")
# dataframe_títulos.sort_values(by=['year'], inplace=True, ascending=True)
# print(dataframe_títulos.head(5))

# dracula_filmes = dataframe_títulos[dataframe_títulos['title'].str.contains("Dracula") | dataframe_títulos['title'].str.contains(
#     "Drácula") | dataframe_títulos['title'].str.contains("dracula") | dataframe_títulos['title'].str.contains("drácula")]
# print("\nFilmes que no título contém a expressão 'Drácula':\n",
#       dracula_filmes, sep="")
# print("\nNúmero total de filmes com a expressão 'Drácula':",
#       dracula_filmes.count()[0])

# groupby_títulos = dataframe_títulos.groupby('title')['title'].count().sort_values(ascending=False)
# print("10 títulos mais comuns:")
# print(groupby_títulos.head(10))


# primeiro_romeo_julieta = dataframe_títulos[dataframe_títulos.title == 'Romeo and Juliet'].sort_values(
#     by=['year'], ascending=True).head(1)
# print("Primeiro filme chamado 'Romeo and Juliet':")
# print(primeiro_romeo_julieta)

# exorcist_filmes = dataframe_títulos[dataframe_títulos['title'].str.contains(
#     "Exorcist") | dataframe_títulos['title'].str.contains("exorcist")].sort_values(by=['year'], ascending=True)
# print("Filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente:")
# print(exorcist_filmes)


Filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente:
                                         title  year
88003                             The Exorcist  1973
49658                  O Exorcista de Mulheres  1974
118920     Satanico Pandemonium: La Sexorcista  1975
140519                Exorcist II: The Heretic  1977
220073                        Kung Fu Exorcist  1978
17375                         The Exorcist III  1990
132451                        Teenage Exorcist  1991
117797                 Exorcist: The Beginning  2004
94189        Dominion: Prequel to the Exorcist  2005
209250  Costa Chica: Confession of an Exorcist  2006
86354                      Exorcist Chronicles  2007
130686                      The Disco Exorcist  2011
57932                      Exorcist Chronicles  2013
151850                              Exorcistas  2015
69974                           Shark Exorcist  2015
51101                            Bad Exorcists  2015
228642        